config/routes.rb
Rails.application.routes.draw do
  root 'instances#new'
  resources :instances, only: [:new, :create, :show, :destroy]

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  # Lets just add a small set of validations, although you would probably
  # need to strongly verify the instances field on a production environment
  validates :access_key, presence: true
  validates :secret_key, presence: true

  after_initialize :defaults

  private

  def defaults
    self.aws_id     ||= 'Not available yet'
    self.status     ||= :initializing
    self.msg        ||= 'Initializing'
    self.location   ||= 'Not available yet'
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :destroy]

  respond_to :html
  respond_to :js, only: [:show]

  def new
    @instance = Instance.new
  end

  def create
    @instance = Instance.new(instance_params)
    LaunchInstanceJob.perform_later @instance if @instance.save
    respond_with @instance
  end

  def show
    respond_with @instance
  end

  def destroy
    if @instance.status.to_sym == :running
      @instance.location = 'Not available'
      @instance.status = :destroying
      @instance.msg = 'Destroying instance'
      @instance.save
      DeleteInstanceJob.perform_later @instance
    end
  end

  private

  def set_instance
    @instance = Instance.find_by(id: params[:id])
  end

  def instance_params
    params.require(:instance)
      .permit(:access_key, :secret_key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_state.html.erb
<article class="instance">
  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <thead>
          <tr>
            <th>AWS Instance ID</th>
            <th>State</th>
            <th>Location</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @instance.aws_id %></td>
            <td><%= @instance.msg %></td>
            <td><%= @instance.location %></td>
            <td>
              <% if @instance.status.to_sym == :running %>
                <%= link_to 'Launch App', "http://#{@instance.location}", :target => '_blank' %>
                <%= link_to 'Destroy', instance_path(@instance), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% elsif @instance.status.to_sym == :error || @instance.status.to_sym == :terminated %>
                <%= link_to 'Launch a new instance', root_path %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</article>

app/views/instances/destroy.html.erb
<%= render 'state' %>

<script type="text/javascript">
  var checker = new StateChecker({
    id: <%= @instance.id %>,
    status: '<%= @instance.status %>'
  });
</script>

app/views/instances/new.html.erb
<article class="form">
  <%= simple_form_for(@instance) do |f| %>
    <%= f.error_notification %>

    <div class="row">
      <div class="col-md-4">
        <%= f.input :access_key %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <%= f.input :secret_key %>
      </div>
    </div>

    <div class="panel-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</article>

app/views/instances/show.html.erb
<%= render 'state' %>

<script type="text/javascript">
  var checker = new StateChecker({
    id: <%= @instance.id %>,
    status: '<%= @instance.status %>'
  });
</script>

app/views/instances/show.js.erb
$('#container').html("<%= escape_javascript(render(:partial => 'instances/state')) %>");
checker.status = '<%= @instance.status %>';

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Launchpad</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div>
        <a class="navbar-brand">Wordpress Launchpad</a>
      </div>
    </nav>
    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>